version: '3'

services:
  
  captivefire:
    build:
      context: '.'
      args: 
        UID: ${UID}
        FOLDER: /app
        USERNAME: captivefire
    image: captivefire:openwrt
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 16M
        reservations:
          memory: 16M
    container_name: captivefire
    # Doesn't work using an init script
    # command: /app/docker/start-container.sh 
    restart: always
    ports:
      - '${APP_HTTP_PORT:-80}:80'
      - 443:443 # HTTPS Port
    volumes:
      - ./docker/etc/config/uhttpd:/etc/config/uhttpd
      - ./docker/etc/php.ini:/etc/php.ini
      - .:/app
