version: '3'

services:
  
  captivefire-uhttpd:
    build:
      context: '.'
    image: captivefire-uhttpd
    container_name: captivefire
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./docker/etc/config/uhttpd:/etc/config/uhttpd
      - ./docker/etc/php.ini:/etc/php.ini
      - .:/app