version: '3'

services:
  
  captivefire:
    build:
      context: '.'
      args: 
        FOLDER: /app/
    image: captivefire:openwrt-2.0
    # Using these directives for 'deploy' we need to run 'docker-compose --compatibility up -d'
    deploy:
      resources:
        limits:
          cpus: '${CPU_MHZ_LIMIT:-0.10}'
          memory: '${RAM_MEMORY_LIMIT:-32M}'
        reservations:
          memory: '${RAM_MEMORY_LIMIT:-32M}'
    container_name: captivefire
    # Doesn't work using an init script
    # command: /app/docker/start-container.sh 
    restart: always
    ports:
      - '8022:22'
      - '${APP_HTTP_PORT:-8000}:80' # HTTP Captivefire
      - '${APP_HTTPS_PORT:-443}:${APP_HTTPS_PORT:-443}' # HTTPS Captivefire
      - '${LUCI_HTTPS_PORT:-8443}:${LUCI_HTTPS_PORT:-8443}' # Luci App
      - '8008:8008'
    volumes:
      - ./docker/etc/config:/etc/config
      - ./docker/etc/crontabs:/etc/crontabs
      - ./docker/etc/php.ini:/etc/php.ini
      - ./docker/etc/rc.local:/etc/rc.local
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
