version: '3'

services:
  
  captivefire-uhttpd:
    build:
      context: '.'
      args: 
        UID: ${UID}
        FOLDER: /app
        USERNAME: captivefire
    image: captivefire-uhttpd
    container_name: captivefire
    # Doesn't work using an init script
    # command: /app/docker/start-container.sh 
    restart: always
    ports:
      - '${APP_HTTP_PORT:-8080}:8080'
      - 8443:8443 # HTTPS Port
    volumes:
      - ./docker/etc/config/uhttpd:/etc/config/uhttpd
      - ./docker/etc/php.ini:/etc/php.ini
      - .:/app